### ISSUE TITLE
Error in elementor 

### ISSUE THREAD

**Issue by olaronymax** [themeum/tutor-elementor-addons#1]
I try create single in theme builder, check the Tutor LMS Single but show error 500.

`AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to a member function have_posts() on bool in /var/www/vhosts/dev.sitedev/httpdocs/devshare/wp-content/plugins/tutor-elementor-addons-master/includes/addons/CoursePrice.php:97\nStack trace:\n#0 /var/www/vhosts/dev.sitedev/httpdocs/devshare/wp-content/plugins/elementor/includes/base/widget-base.php(530): TutorLMS\\Elementor\\Addons\\CoursePrice->render()\n#1 /var/www/vhosts/dev.sitedev/httpdocs/devshare/wp-content/plugins/elementor/core/base/document.php(230): Elementor\\Widget_Base->render_content()\n#2 /var/www/vhosts/dev.sitedev/httpdocs/devshare/wp-content/plugins/elementor-pro/modules/theme-builder/documents/theme-document.php(409): Elementor\\Core\\Base\\Document->render_element(Array)\n#3 /var/www/vhosts/dev.sitedev/httpdocs/devshare/wp-content/plugins/elementor/includes/managers/widgets.php(323): ElementorPro\\Modules\\ThemeBuilder\\Documents\\Theme_Document->render_element(Array)\n#4 [internal function]: Elementor\\Widgets_Manager->ajax_...', referer: https://dev.site.com/devshare/wp-admin/post.php?post=2231&action=elementor	`

**Comment by sksaju** [comment]
Your mentioned error is fixed, thanks for noticing @ronymax 
FYI, This plugin is not ready for production yet, we are trying to release v1.0 this month
