### ISSUE TITLE
There has been a critical error on your website.

### ISSUE THREAD

**Issue by Lifeischoice** [themeum/tutor-elementor-addons#5]
This error "There has been a critical error on your website" is shown when the plugin is activated on my site. The plugin installed okay but will not allow display of any page on the site. The display of the site returned to normal when the plugin is deactivated.
The site error log has this - "PHP Parse error:  syntax error, unexpected ')' in /home/mywebsite/public_html/my/wp-content/plugins/tutor-elementor-addons-master/includes/addons/CourseCarousel.php on line 841".

**Comment by sksaju** [comment]
@Lifeischoice thanks for reporting the error, please update your plugin from this repository, and let us know your feedback

**Comment by Lifeischoice** [comment]
I have re-downloaded and re-installed....same website issue/error "There has been a critical error on your website"...however, the site error log now show "/home/mindbasi/public_html/my/wp-content/plugins/tutor-elementor-addons-master/includes/addons/CourseList.php on line 953"

**Comment by sksaju** [comment]
Ok the error has been resolved thank you again @Lifeischoice

**Comment by Lifeischoice** [comment]
Thank you...that worked!
