### ISSUE TITLE
Ability to Disable Biography in Course Instructors widget

### ISSUE THREAD

**Issue by kitusmark** [themeum/tutor-elementor-addons#8]
It would be great to be able to disable the biography in the Course Instructors list widget. Normally bios are 3-4 paragraphs long and if you put the instructor list on a sidebar, the section grows too tall. 
I'd like to disable bio in course instructors widget but keep it in the instructor's public profile page. 

That would be awesome!
Thanks.

**Comment by shewa12** [comment]
Okay we will try to consider it. Thanks.
